### PR TITLE
fix a npe in WarpScript exception message

### LINKED ISSUE #981: maxops error regression
Hi,

Between 2.7 and 2.8, there is a regression in the maxops reached error message.

For example:

```
'validtoken' AUTHENTICATE
6000 MAXOPS

[
  1 200 <% DROP NEWGTS %> FOR
] 'list' STORE

$list
<%
  'l' STORE
  $list
  <%
    'j' STORE
  %> FOREACH
%> FOREACH
```

leads to `Exception at '%> =>FOREACH<=' in section [TOP] (Exception at 'FOREACH' in section '[TOP]')`.

### PR DESCRIPTION
**Pull request by pi-r-p**
fix #981

### CODE REVIEW

File: warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java [hunk 1]
```diff
@@ -985,7 +985,10 @@ public void exec(Macro macro) throws WarpScriptException {
         String name = macro.getName();
         String section = (String) this.getAttribute(WarpScriptStack.ATTRIBUTE_SECTION_NAME);
         Object statement = macro.get(i);
-        String statementString = statement.toString();
+        String statementString = "";
```
Comment (hbs) [inline warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java:988]: Do we want to have the empty String is statement is null or null?

File: warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java [hunk 2]
```diff
@@ -984,9 +984,10 @@ public void exec(Macro macro) throws WarpScriptException {
       } else {
         String name = macro.getName();
         String section = (String) this.getAttribute(WarpScriptStack.ATTRIBUTE_SECTION_NAME);
-        Object statement = macro.get(i);
         String statementString = "";
-        if (null != statement) {
+        Object statement = null;
+        if (i >= macro.size()) {
+          statement = macro.get(macro.size() - 1);
```
Comment (hbs) [inline warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java:990]: The statementString = statement.toString() should be outside of the conditional and statement should be initialized to macro.get(i), not to null.

Comment (hbs) [reply warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java:990]: And statementString should be set to String.valueOf(statement)

**Review by ftence — APPROVED** [review]
