### PR TITLE
Fixes #708 - Corrected pre/post window handling.

### LINKED ISSUE #708: incorrect argument count in MACROFILLER when pre/post window are 0

### PR DESCRIPTION
**Pull request by hbs**

### CODE REVIEW

File: warp10/src/main/java/io/warp10/script/functions/MACROFILLER.java [hunk 1]
```diff
@@ -100,9 +101,23 @@ public int getPostWindow() {
...
 
       long ts = 0L;
+                  
+      //
+      // The args array starting at index 1 contains one element per preWindow tick,
+      // the current tick of the other GTS and one element per postWindow tick
+      //
       
+      int preWindowCount = this.preWindow;
+      int postWindowCount = this.postWindow;
```
Comment (ftence) [inline warp10/src/main/java/io/warp10/script/functions/MACROFILLER.java]: Unused.
